export { AgentDO, ChatDO, TerminalDO } from "./durable-objects";
// Generated by `opennextjs-cloudflare build` before preview/deploy.
// @ts-ignore .open-next is generated output and absent during plain typecheck.
import openNextHandler from "../../.open-next/worker.js";
import { Effect } from "effect";
import { runAutomaticDeploymentUpdatesFromEnvEffect } from "../lib/deployment-update";
import type { D1DatabaseLike } from "../lib/d1";
import { resolveDeploymentRepository } from "../lib/repositories";
import { runAutomaticSyncFromEnvEffect } from "../lib/sync-service";

type WorkerHandler = {
  fetch(
    request: Request,
    env: Record<string, unknown>,
    ctx: WorkerExecutionContext
  ): Promise<Response> | Response;
};

type WorkerExecutionContext = {
  waitUntil(promise: Promise<unknown>): void;
  passThroughOnException?(): void;
};

type OpenNextModule = {
  fetch?: WorkerHandler["fetch"];
};

export default {
  async fetch(
    request: Request,
    env: Record<string, unknown>,
    ctx: WorkerExecutionContext
  ): Promise<Response> {
    const handler = openNextHandler as OpenNextModule;
    if (handler.fetch) {
      return handler.fetch(request, env, ctx);
    }

    const assets = env.ASSETS as { fetch?: (request: Request) => Promise<Response> } | undefined;
    if (assets?.fetch) {
      return assets.fetch(request);
    }

    return Response.json(
      {
        error: "OpenNext worker output is missing. Run the platform Worker build before deploying."
      },
      { status: 503 }
    );
  },
  async scheduled(
    _controller: { cron: string; scheduledTime: number },
    env: Record<string, unknown>,
    ctx: WorkerExecutionContext
  ): Promise<void> {
    const db = isD1DatabaseLike(env.DB) ? env.DB : undefined;
    const repository = resolveDeploymentRepository(db ? { DB: db } : {}, env);
    ctx.waitUntil(
      Effect.runPromise(
        Effect.all(
          [
            runAutomaticSyncFromEnvEffect(env),
            runAutomaticDeploymentUpdatesFromEnvEffect(repository.repository, env)
          ],
          {
            concurrency: 2,
            discard: true
          }
        )
      )
    );
  }
};

function isD1DatabaseLike(value: unknown): value is D1DatabaseLike {
  return Boolean(
    value &&
      typeof value === "object" &&
      typeof (value as { prepare?: unknown }).prepare === "function"
  );
}
